apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testflaskservice
  labels:
    app: testflaskservice
    aadpodidbinding: msitestservice_it
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: testflaskservice
        aadpodidbinding: msitestservice_it
    spec:
      containers:
      - name: testflaskservice
        image: testflaskserviceacr.azurecr.io/testflaskservice
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: keyvaulturl
          value: "https://testflaskservicekv.vault.azure.net"
---
apiVersion: v1
kind: Service
metadata:
  name: testflaskservice-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: testflaskservice
